logging:
  pattern:
    console: "[PracticalJava] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "[PracticalJava] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: log/practical-java.log
    
spring:
  main:
    banner-mode: OFF
  jackson:
    property-naming-strategy: SNAKE_CASE
    
server:
  port: 8001

management:
  metrics:
    export:
      elastic:
        step: 30s
        host: http://localhost:9200

# Hide "Try it out" button on Spring Doc for sharing documentation.
# "Try it out" button only enabled for "get" APIs.
springdoc:
  swagger-ui:
    supported-submit-methods:
    - get
    
 